theme: jekyll-theme-hacker
show_downloads: false
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
collections:
  - artwork